[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vim-pytoy"
version = "0.1.0"
description = "Python utility for Vim/Neovim + VSCode integration"
dependencies = [
    "ipython>=8.14",
    "psutil>=5.9",
    "pydantic>=2.0.0",
    "pynvim>=0.5",
    "pyte>=0.8",
    "toml>=0.10",
    "pip-system-certs>=0.1",
    "markitdown>=0.0.1",
    "requests>=2.31",
    "pywinpty; sys_platform == 'win32'",
    "pexpect; sys_platform == 'linux'",
    "pytoy-llm @ git+https://github.com/Sillte/pytoy-llm.git@main",
]
requires-python = ">=3.12"


[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["pythonx"]
addopts = "-v"

[tool.setuptools.packages.find]
where = ["pythonx"]

[dependency-groups]
dev = [
    "pytest>=7.0.0",
    "ruff>=0.15",
    "ty", 
    "mypy>=1.14.1",
    "prek",
    "pexpect",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]

select = ["E", "F", "I"]
ignore = [
    "E501", # Exclude specific rule: Line too long
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
known-first-party = ["pytoy", "pytoy-llm"]


[tool.ty.analysis]
allowed-unresolved-imports = [
    "vim",
]

[tool.ty.src]
exclude = [
    "tests_vim",
    "tests/mocks"
]



