from typing import Any

def command(cmd: str) -> None: ...
def eval(expr: str) -> Any: ...
def bindeval(expr: str) -> Any: ...
def vars() -> dict[str, Any]: ...
class Current:
    buffer: Any
    window: Any
    tabpage: Any
    line: str
current: Current

def Function(cmd: str) ->Any: ...
