from typing import Any, Sequence

def command(cmd: str) -> None: ...
def eval(expr: str) -> Any: ...
def bindeval(expr: str) -> Any: ...

# def vars() -> dict[str, Any]: ...
vars: dict[str, Any]



class Buffer:
    def __getitem__(self, name: Any) -> Any: ...
    def __setitem__(self, name: Any, value: Any) -> None: ...
    def __call__(self, *args, **kwargs) -> Any: ...
    def __len__(self) -> int: ...
    @property
    def valid(self) -> bool: ...
    @property
    def number(self) -> int: ...
    @property
    def name(self) -> str: ...
    def append(self, line: str): ...
    @property
    def lines(self) -> list[str]: ...

class Window:
    def __getattr__(self, name: str) -> Any: ...
    def __setitem__(self, name: Any, value: Any) -> None: ...
    def __call__(self, *args, **kwargs) -> Any: ...

    @property
    def cursor(self) -> tuple[int, int]: ...

    @cursor.setter
    def cursor(self, value: tuple[int, int]) -> None: ...

class Tabpage: 
    @property
    def windows(self) -> Sequence[Window]: ...

class Current:
    buffer: Buffer
    window: Window
    tabpage: Tabpage
    line: str

current: Current

options: Any
buffers: list[Buffer]
windows: list[Window]
tabpages: list[Tabpage]
