from typing import Protocol, Sequence

from pytoy.shared.ui.contract.quickfix.models import QuickfixRecord, QuickfixState


class PytoyQuickfixProtocol(Protocol):
    def set_records(self, records: Sequence[QuickfixRecord]) -> QuickfixState: ...

    def open(self) -> None: ...

    def close(self) -> None: ...

    def jump(self, state: int | QuickfixState | None = None) -> QuickfixRecord | None: ...

    def move(self, diff_index: int) -> QuickfixRecord | None: ...

    @property
    def records(self) -> Sequence[QuickfixRecord]: ...

    @property
    def state(self) -> QuickfixState | None: ...


class PytoyQuickfixUIProtocol(Protocol):
    def set_records(self, records: Sequence[QuickfixRecord]) -> QuickfixState: ...

    def open(self) -> None: ...

    def close(self) -> None: ...

    def jump(self, state: QuickfixState) -> QuickfixRecord | None: ...

    @property
    def records(self) -> Sequence[QuickfixRecord]: ...

    @property
    def state(self) -> QuickfixState | None: ...


class QuickfixViewerProtocol(Protocol):
    def show(self) -> None: ...

    def close(self) -> None: ...

    def jump(self, *, with_focus: bool = False) -> QuickfixRecord | None: ...

    def sync_to_ui(self, only_index: bool = True) -> None: ...

    def sync_from_ui(self, only_index: bool = True) -> None: ...


__all__ = [
    "PytoyQuickfixProtocol",
    "PytoyQuickfixUIProtocol",
    "QuickfixViewerProtocol",
    "QuickfixRecord",
    "QuickfixState",
]
