from typing import Protocol, Any, Sequence, Self
from pytoy.ui.pytoy_quickfix.models import QuickfixRecord, QuickfixState


class PytoyQuickfixProtocol(Protocol):
    """Quickfix-like Protocol."""

    def set_records(self, records:  Sequence[QuickfixRecord]) -> QuickfixState: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def jump(self, state: int | QuickfixState | None = None) -> QuickfixRecord | None: ...
    def move(self, diff_index: int) -> QuickfixRecord | None: ...


class PytoyQuickfixStateResolverProtocol(Protocol):
    def resolve_record(self, records: Sequence[QuickfixRecord], state: QuickfixState) -> QuickfixRecord | None: ...
    def shift_index(self, state: QuickfixState, diff_index: int) -> QuickfixState: ...
    def fix_index(self, state: QuickfixState, index: int) -> QuickfixState: ...


class PytoyQuickfixUIProtocol(Protocol):
    """Quickfix-UIlike Protocol."""

    def set_records(self, records:  Sequence[QuickfixRecord]) -> QuickfixState: ...

    def open(self) -> None: ...

    def close(self) -> None: ...

    def jump(self, state: QuickfixState) -> QuickfixRecord | None: ...

    @property
    def records(self) -> Sequence[QuickfixRecord]: ...

    @property
    def state(self) -> QuickfixState | None: ...
