from typing import Protocol, Any, Sequence, Self
from pytoy.ui.pytoy_quickfix.models import QuickFixRecord, QuickFixState


class PytoyQuickFixProtocol(Protocol):
    """QuickFix-like Protocol."""

    def set_records(self, records:  Sequence[QuickFixRecord]) -> QuickFixState: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def jump(self, state: int | QuickFixState | None = None) -> QuickFixRecord | None: ...
    def move(self, diff_index: int) -> QuickFixRecord | None: ...


class PytoyQuickFixStateResolverProtocol(Protocol):
    def resolve_record(self, records: Sequence[QuickFixRecord], state: QuickFixState) -> QuickFixRecord | None: ...
    def shift_index(self, state: QuickFixState, diff_index: int) -> QuickFixState: ...
    def fix_index(self, state: QuickFixState, index: int) -> QuickFixState: ...


class PytoyQuickFixUIProtocol(Protocol):
    """QuickFix-UIlike Protocol."""

    def set_records(self, records:  Sequence[QuickFixRecord]) -> QuickFixState: ...

    def open(self) -> None: ...

    def close(self) -> None: ...

    def jump(self, state: QuickFixState) -> QuickFixRecord | None: ...

    @property
    def records(self) -> Sequence[QuickFixRecord]: ...

    @property
    def state(self) -> QuickFixState | None: ...
