from typing import Protocol, Any, Sequence
from pytoy.ui.pytoy_quickfix.models import QuickFixRecord


class PytoyQuickFixProtocol(Protocol):
    """QuickFix-like Protocol."""

    def setlist(self, records: Sequence[QuickFixRecord], win_id: int | None = None) -> None: ...

    def getlist(self, win_id: int | None = None) -> Sequence[QuickFixRecord]: ...

    def close(self, win_id: int | None = None) -> None: ...

    def open(self, win_id: int | None = None) -> None: ...

    def go(self, idx: int | None = None, win_id: int | None = None) -> None: ...

    def next(self, win_id: int | None = None) -> None: ...

    def prev(self, win_id: int | None = None) -> None: ...
